FC = gfortran
FFLAGS = -O2 -ffast-math -w

#FILES = global.f90 ffpar.f90 config.f90 trajecta.f90
FILES = trajecta.f90

all: clean

trajecta: $(FILES)
	$(FC) $(FFLAGS) -o $@ $(FILES)

clean: trajecta
	rm *.mod
